sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '4'
script:
  - make
after_success:
  - yarn semantic-release
branches:
  only:
    - master